front:
  build: .
  ports:
    - "8887:80"
    - "443:443"
  links:
    - mysql:mysql
    - redis:redis
  volumes:
    - ./www:/var/www
    - ./docker/conf:/opt/conf
    - ./docker/sites:/etc/nginx/conf.d

mysql:
  image: mysql
  ports:
    - "3307:3306"
  environment:
    MYSQL_ROOT_PASSWORD: password
    MYSQL_DATABASE: homestead
    MYSQL_USER: homestead
    MYSQL_PASSWORD: secret

redis:
  image: redis
  ports:
    - "6379:6379"